run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gosec
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  
  goimports:
    local-prefixes: github.com/victalejo/tradeoptix-backend
  
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/
      linters:
        - errcheck
    - path: migrations/
      linters:
        - errcheck
  
  max-issues-per-linter: 50
  max-same-issues: 10