#!/bin/bash

echo "🚀 GUÍA PARA DESPLEGAR A PRODUCCIÓN"
echo "=================================="
echo ""
echo "🎯 PROBLEMA IDENTIFICADO:"
echo "Tu servidor de producción (https://api.tradeoptix.app) solo tiene la ruta /health"
echo "Las rutas de admin (/api/v1/admin/news, /api/v1/admin/notifications) NO existen"
echo ""
echo "✅ CORS está configurado correctamente en producción"
echo "❌ Las rutas de la aplicación NO están desplegadas"
echo ""
echo "🔥 SOLUCIÓN: DESPLEGAR EL CÓDIGO ACTUAL A PRODUCCIÓN"
echo ""
echo "📋 PASOS PARA DEPLOYMENT:"
echo ""
echo "1. COMPILAR LA APLICACIÓN:"
echo "   make build"
echo ""
echo "2. SUBIR AL SERVIDOR (usando la IP que encontramos):"
echo "   # IP del servidor: 194.163.133.7"
echo "   scp bin/tradeoptix-server usuario@194.163.133.7:/ruta/del/servidor/"
echo ""
echo "3. CONFIGURAR VARIABLES DE ENTORNO EN PRODUCCIÓN:"
echo "   # Crear .env en el servidor con:"
cat << 'EOF'
PORT=8080
ENVIRONMENT=production
DATABASE_URL=postgresql://tradeoptix_user:nrdys53kzx8amg50@tradeoptix-dbprincipal-exnswt:5432/tradeoptix_db?sslmode=disable
JWT_SECRET=dJxPh6PwKyyZcVRnVkbzMY51SftP37fy
ALLOWED_ORIGINS=https://admin.tradeoptix.app,https://app.tradeoptix.app,https://tradeoptix.app
EOF
echo ""
echo "4. REINICIAR EL SERVICIO EN PRODUCCIÓN:"
echo "   systemctl restart tradeoptix-server"
echo "   # o el comando que uses para reiniciar"
echo ""
echo "🔧 ALTERNATIVAS DE DEPLOYMENT:"
echo ""
echo "A. DOCKER:"
echo "   docker build -t tradeoptix-backend ."
echo "   docker push tu-registry/tradeoptix-backend"
echo "   # Deploy en el servidor"
echo ""
echo "B. CI/CD (GitHub Actions, etc):"
echo "   - Push to main branch"
echo "   - Automatic deployment"
echo ""
echo "C. SERVIDOR LOCAL EXPUESTO:"
echo "   # Si quieres usar tu servidor local temporalmente:"
echo "   # Configurar reverse proxy (nginx) o tunnel"
echo ""
echo "💡 VERIFICACIÓN POST-DEPLOYMENT:"
echo "curl -s https://api.tradeoptix.app/api/v1/admin/news"
echo "# Debería devolver data, no 404"
echo ""
echo "🎯 RESULTADO ESPERADO:"
echo "Una vez desplegado, https://admin.tradeoptix.app funcionará completamente"